# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jame0313.github.io
brief-intro: cheong-jeong-su student
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jame0313.github.io" # the base hostname & protocol for your site

permalink: /:year/:month/:day/:title/

# other links
github_username:  jame0313
email: jame0313@naver.com

description_footer: 청정하다 청정해

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
disqus_shortname: jame0313

# statistic analysis 统计代码
google_analytics_id: UA-127579956-1

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
